// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

import 'package:flutter_dotenv/flutter_dotenv.dart';


/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions web = FirebaseOptions(
    apiKey: dotenv.env['apiWeb'].toString(),
    appId: '1:976548096870:web:5930f122e67dee588536a7',
    messagingSenderId: '976548096870',
    projectId: 'happyo-dev',
    authDomain: 'happyo-dev.firebaseapp.com',
    storageBucket: 'happyo-dev.appspot.com',
  );

  static FirebaseOptions android = FirebaseOptions(
    apiKey: dotenv.env['apiAndroid'].toString(),
    appId: '1:976548096870:android:7d8a56606385811f8536a7',
    messagingSenderId: '976548096870',
    projectId: 'happyo-dev',
    storageBucket: 'happyo-dev.appspot.com',
  );

  static FirebaseOptions ios = FirebaseOptions(
    apiKey: dotenv.env['apiIos'].toString(),
    appId: '1:976548096870:ios:8dbe67d0b32de67e8536a7',
    messagingSenderId: '976548096870',
    projectId: 'happyo-dev',
    storageBucket: 'happyo-dev.appspot.com',
    iosClientId: '976548096870-cch461jgleg6ck2mrlcgckn6dnod0la4.apps.googleusercontent.com',
    iosBundleId: 'com.example.happyo',
  );

  static FirebaseOptions macos = FirebaseOptions(
    apiKey: dotenv.env['apiIos'].toString(),
    appId: '1:976548096870:ios:8dbe67d0b32de67e8536a7',
    messagingSenderId: '976548096870',
    projectId: 'happyo-dev',
    storageBucket: 'happyo-dev.appspot.com',
    iosClientId: '976548096870-cch461jgleg6ck2mrlcgckn6dnod0la4.apps.googleusercontent.com',
    iosBundleId: 'com.example.happyo',
  );

}
